### ISSUE TITLE
How to contextually search through heaps of memes ?

### ISSUE THREAD

**Issue by alt-shreya** [alt-shreya/faq-jina-ai#20]
~ asked by Anjali Kumawat

**Comment by alt-shreya** [comment]
This is the experience Power of Jina first hand by trying out this http://examples.jina.ai/memes/ example that uses Jina’s neural search framework to contextually search through heaps of memes.                                                                                                                                                                                            The Meme search provides two modes of search.                                                                                                                                      -  text-to-text                                                                                                                                                                                                           -  image-to-image

~ answered by Anjali Kumawat

**Comment by alt-shreya** [comment]
@alexcg1 I assigned this the label "invalid" as I think this isn't asked frequently. Could you please review it?

**Comment by alexcg1** [comment]
Agreed
